/**
 * Invoice (subscription billing) client for the MercadoPago API.
 *
 * Provides methods to retrieve and search subscription invoices
 * (authorized payments) generated by recurring preapprovals.
 *
 * @module invoice
 */

import get from './get';
import search from './search';

import type { InvoiceResponse } from './commonTypes';
import type { InvoiceGetData } from './get/types';
import type { InvoiceSearchData, InvoiceSearchResponse } from './search/types';

import type { MercadoPagoConfig } from '@src/mercadoPagoConfig';

/**
 * Client facade for MercadoPago subscription invoice operations.
 *
 * Use this class to fetch a single invoice by ID or to search invoices
 * by subscription, payer, or payment criteria.
 */
export class Invoice {
	/** SDK configuration providing credentials and HTTP options. */
	private config: MercadoPagoConfig;

	constructor(mercadoPagoConfig: MercadoPagoConfig) {
		this.config = mercadoPagoConfig;
	}

	/**
	 * Retrieve a single subscription invoice by its ID.
	 *
	 * @see {@link https://github.com/mercadopago/sdk-nodejs/blob/master/src/examples/invoice/get.ts Usage Example }.
	 */
	get({ id, requestOptions }: InvoiceGetData): Promise<InvoiceResponse> {
		this.config.options = { ...this.config.options, ...requestOptions };
		return get({ id, config: this.config });
	}

	/**
	 * Search subscription invoices with optional filters.
	 *
	 * Filters include preapproval ID, payer ID, payment ID, and pagination.
	 *
	 * @see {@link https://github.com/mercadopago/sdk-nodejs/blob/master/src/examples/invoice/search.ts Usage Example }.
	 */
	search(ivoicesSearchOptions: InvoiceSearchData = {}): Promise<InvoiceSearchResponse> {
		const { options, requestOptions } = ivoicesSearchOptions;
		this.config.options = { ...this.config.options, ...requestOptions };
		return search({ options, config: this.config });
	}
}
